### ISSUE TITLE
Install dependencies

### ISSUE THREAD

**Issue by son0p** [rvega/window-positions#3]
I cloned the repo but I am having this error when I try the command

ff➜  window-positions : master ✔ : ᐅ  sudo install dependencies  
install: missing destination file operand after ‘dependencies’  
Try 'install --help' for more information.

**Comment by rvega** [comment]
Ah! That's a typo on the readme. All the install scripts are based on a makefile so the right command to use is:

$ sudo make install-dependencies

I'll fix the README now.

**Comment by rvega** [comment]
https://github.com/rvega/window-positions/commit/1ee7f2c1eb3198ff7986b79026b7638bec548bb4
